GameObject g = new GameObject(); 
            Canvas canvas = g.AddComponent<Canvas>(); 
            canvas.renderMode = RenderMode.WorldSpace; 
            CanvasScaler cs = g.AddComponent<CanvasScaler>(); 
            cs.scaleFactor = 10.0f; 
            cs.dynamicPixelsPerUnit = 10f; 
            GraphicRaycaster gr = g.AddComponent<GraphicRaycaster>(); 
            g.GetComponent<RectTransform>().SetSizeWithCurrentAnchors(RectTransform.Axis.Horizontal, 3.0f); 
            g.GetComponent<RectTransform>().SetSizeWithCurrentAnchors(RectTransform.Axis.Vertical, 3.0f); 
            GameObject g2 = new GameObject(); 
            g2.name = "Text"; 
            g2.transform.parent = g.transform; 
            Text t = g2.AddComponent<Text>(); 
            g2.GetComponent<RectTransform>().SetSizeWithCurrentAnchors(RectTransform.Axis.Horizontal, 3.0f); 
            g2.GetComponent<RectTransform>().SetSizeWithCurrentAnchors(RectTransform.Axis.Vertical, 3.0f); 
            t.alignment = TextAnchor.MiddleCenter; 
            t.horizontalOverflow = HorizontalWrapMode.Overflow; 
            t.verticalOverflow = VerticalWrapMode.Overflow; 
            Font ArialFont = (Font)Resources.GetBuiltinResource(typeof(Font), "Arial.ttf"); 
            t.font = ArialFont; 
            t.fontSize = 7; 
            t.text = "Test"; 
            t.enabled = true; 
            t.color = Color.black; 

            g.name = "Text Label"; 
